[project]
name = "django-p35"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.8",
    "pillow>=12.0.0",
    "psycopg2-binary>=2.9.11",
]
